name: reio
description: Reio.dart is a progressive, incrementally-adoptable Dart framework for building UI on the test.
version: 0.1.0
homepage: https://github.com/MineEjo/reiodart
repository: https://github.com/MineEjo/reiodart
issue_tracker: https://github.com/MineEjo/reiodart/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
