#  format: dart format .
#  publish: dart pub publish --dry-run

name: reio
description: Reio.dart is a progressive Dart framework for creating UI on the web. Uses HTML, CSS and Dart, which is compiled into efficient JavaScript code.
version: 0.2.0
homepage: https://github.com/MineEjo/reiodart
repository: https://github.com/MineEjo/reiodart
issue_tracker: https://github.com/MineEjo/reiodart/issues
documentation: https://mineejo.github.io/reiodart/

platforms:
  web:

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.1
