#  publish: dart pub publish --dry-run

name: reio
description: Reio.dart is a progressive Dart library for creating UI on the web.
version: 0.1.4
homepage: https://github.com/MineEjo/reiodart
repository: https://github.com/MineEjo/reiodart
issue_tracker: https://github.com/MineEjo/reiodart/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.1
