name: reio_css
description: The official responsive web interface for Reio.dart. Ready-to-use frontend components.
version: 0.2.6+1.0.0
homepage: https://reiodart.vercel.app
repository: https://github.com/MineEjo/reiodart/tree/master/packages/css
issue_tracker: https://github.com/MineEjo/reiodart/issues
documentation: https://mineejo.github.io/reiodart

# scripts:
#   format: dart format .
#   publish: dart pub publish --dry-run

platforms:
  web:

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  reio: ^0.2.6

dev_dependencies:
  lints: ^2.0.1
