#  format: dart format .
#  publish: dart pub publish --dry-run

name: reio_router
description: The official router for Reio.dart. Single-page application routing.
version: 0.2.4+1.0.1
homepage: https://reiodart.vercel.app
repository: https://github.com/MineEjo/reiodart/tree/master/packages/router
issue_tracker: https://github.com/MineEjo/reiodart/issues
documentation: https://mineejo.github.io/reiodart

platforms:
  web:

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  reio: ^0.2.4

dev_dependencies:
  lints: ^2.0.1
