name: reio
description: Reio is a progressive Dart framework for creating UI on the web. Uses HTML, CSS and Dart, which is compiled into efficient JavaScript code.
version: 0.2.4
homepage: https://reiodart.vercel.app
repository: https://github.com/MineEjo/reiodart
issue_tracker: https://github.com/MineEjo/reiodart/issues
documentation: https://mineejo.github.io/reiodart

# scripts:
#   format: dart format .
#   publish: dart pub publish --dry-run
#   test: dart test

platforms:
  web:

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  test: ^1.23.0
  lints: ^2.0.1
