name: website

# scripts:
#   format: dart format .
#   dev: webdev serve --auto=refresh
#   test: dart run build_runner test -- -p firefox
#   build: webdev build --release --output ./website

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  test: ^1.23.0
  build_runner: ^2.3.3
  build_test: ^2.1.6
  build_web_compilers: ^3.2.7
  lints: ^2.0.1
  reio:
    path: ../core
