name: Running unit tests

on: [ push, pull_request, workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.4

      - run: firefox --version

      - name: Install desktop
        run: |
          export DISPLAY=0:0
          sudo apt-get install openbox

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test -r github
