name: Running unit tests

on: [ push, pull_request, workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.4

      - name: Install desktop
        run: sudo apt-get install openbox

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          dart test -r github -p chrome
